### ISSUE TITLE
Is ProxyPanel already supported?

### ISSUE THREAD

**Issue by AMAU1126** [AikoXrayR-Project/XrayR#37]
**Mô tả các lựa chọn thay thế bạn đã xem xét** 
Is it possible to compare the code of the two projects to see if the ProxyPanel is fully supported?
When not supported Is it possible to port the code directly?

[Projects that have fully implemented ProxyPanel](https://github.com/missuo/XrayR)
[current project](https://github.com/AikoXrayR-Project/XrayR)
Thêm bất kỳ bối cảnh hoặc ảnh chụp màn hình bổ sung nào về yêu cầu tính năng tại đây.
![image](https://user-images.githubusercontent.com/96520210/177529203-72a1a780-37d2-4ac0-99e8-53cee0dee8b0.png)

**Comment by AikoCute-Offical** [comment]
Yes , it is supported is proxy panel .

**Comment by AMAU1126** [comment]
> Yes , it is supported is proxy panel .

![image](https://user-images.githubusercontent.com/96520210/177530319-e2d45a97-70ae-4a8a-b879-f8b7a2ac3e96.png)

**Comment by AikoCute-Offical** [comment]
I fixed it a long time ago but I forgot to edit readme.ms

**Comment by AMAU1126** [comment]
> I fixed it a long time ago but I forgot to edit readme.ms

Thank you so much, this sounds great.

**Comment by AikoCute-Offical** [comment]
![3D091B25-F2D0-43A5-B2A3-EAC110C1F431](https://user-images.githubusercontent.com/91626055/177530693-779ad801-ff0b-4f12-813f-b98c4ab013b1.png)
It is updated
