### ISSUE TITLE
Can you update redis pls

### ISSUE THREAD

**Issue by aqvpnservices** [AikoXrayR-Project/XrayR#38]
If there is redis then the ability to limit the device will be better.

Can you add this feature pls

**Comment by AikoCute-Offical** [comment]
Redis or redis sever ?

**Comment by AMAU1126** [comment]
> Redis or redis sever ?

He wants you to add the ability to connect to the Redis server to limit the number of device connections.

But I don't feel good about it.

**Comment by AikoCute-Offical** [comment]
Why do you think so, can you give me a specific reason for the benefit

**Comment by AMAU1126** [comment]
> 

This increases the complexity of the configuration and adds one more middleware.

**Comment by AMAU1126** [comment]
> Why do you think so, can you give me a specific reason for the benefit

This increases the complexity of the configuration and adds one more middleware.

**Comment by AikoCute-Offical** [comment]
> > Why do you think so, can you give me a specific reason for the benefit
> 
> This increases the complexity of the configuration and adds one more middleware.

I'm feeling the idea of adding redis to limit members is also a good idea, but I'm thinking about how to develop it optimally. do you mean

**Comment by AMAU1126** [comment]
It would be better if the configuration on the panel exceeds the limit of the number of devices and bans

**Comment by AMAU1126** [comment]
> I'm feeling the idea of adding redis to limit members is also a good idea, but I'm thinking about how to develop it optimally. do you mean

Add a switch to enable or disable restricting devices via Redis. default off

**Comment by AikoCute-Offical** [comment]
> > I'm feeling the idea of adding redis to limit members is also a good idea, but I'm thinking about how to develop it optimally. do you mean
> 
> Add a switch to enable or disable restricting devices via Redis. default off

i am thinking how to connect to redis db

**Comment by AMAU1126** [comment]
> > > I'm feeling the idea of adding redis to limit members is also a good idea, but I'm thinking about how to develop it optimally. do you mean
> > 
> > 
> > Add a switch to enable or disable restricting devices via Redis. default off
> 
> i am thinking how to connect to redis db

Hope it doesn't affect the connection performance of the node

**Comment by AMAU1126** [comment]
@AikoCute-Offical How would you judge the number of devices? every time the device connects to the node?

**Comment by AikoCute-Offical** [comment]
> @AikoCute-Offical How would you judge the number of devices? every time the device connects to the node?

I think so too, and I intend for config to be a concatenated file like Block domain file ( Rulelist )

**Comment by AMAU1126** [comment]
> > @AikoCute-Offical How would you judge the number of devices? every time the device connects to the node?
> 
> I think so too, and I intend for config to be a concatenated file like Block domain file ( Rulelist )

Will each judgment increase the connection time?

**Comment by AMAU1126** [comment]
Especially when there is a single Redis node and it is far away from the XrayR server.

**Comment by AikoCute-Offical** [comment]
> Especially when there is a single Redis node and it is far away from the XrayR server.

That's why I thought that if users use Limit devices, they have to trade off performance on each node and go through an intermediate step of Redis .

**Comment by AMAU1126** [comment]
> > Especially when there is a single Redis node and it is far away from the XrayR server.
> 
> That's why I thought that if users use Limit devices, they have to trade off performance on each node and go through an intermediate step of Redis .

Ok, just do it.

**Comment by AikoCute-Offical** [comment]
> > > Especially when there is a single Redis node and it is far away from the XrayR server.
> > 
> > 
> > That's why I thought that if users use Limit devices, they have to trade off performance on each node and go through an intermediate step of Redis .
> 
> Ok, just do it.

Are you a DEV , if you can support me to do it . I'm thinking how to optimize the code after adding it.

**Comment by AMAU1126** [comment]
> Are you a DEV , if you can support me to do it . I'm thinking how to optimize the code after adding it.

I'm a developer, but I'm not a go lang developer.

**Comment by AikoCute-Offical** [comment]
That sounds really sad.....

> > Are you a DEV , if you can support me to do it . I'm thinking how to optimize the code after adding it.
> 
> I'm a developer, but I'm not a go lang developer.

That sounds really sad.....

**Comment by AMAU1126** [comment]
> That sounds really sad.....
> 
> > > Are you a DEV , if you can support me to do it . I'm thinking how to optimize the code after adding it.
> > 
> > 
> > I'm a developer, but I'm not a go lang developer.
> 
> That sounds really sad.....

It can be modified in its original code to limit the number of devices.

**Comment by AMAU1126** [comment]
![图片](https://user-images.githubusercontent.com/96520210/177684102-febb219b-902d-4b39-b48b-fc9024286af1.png)

Looking at the code, I feel that the original limited number of devices is okay.
If you add Redis, you will at most change the api call method to query Redis.

**Comment by AikoCute-Offical** [comment]
Should I split it into 2 functions?

**Comment by AMAU1126** [comment]
> Should I split it into 2 functions?

You can do this, determine whether Redis is enabled, and then call a different method.

**Comment by AikoCute-Offical** [comment]
> > Should I split it into 2 functions?
> 
> You can do this, determine whether Redis is enabled, and then call a different method.

okey , i'll try it

**Comment by AikoCute-Offical** [comment]
Update Compelete Redis But .............

**Comment by AikoCute-Offical** [comment]
- has a fun device limit function
https://github.com/AikoCute-Offical/IpRecorder
