### ISSUE TITLE
how to Support Shadowsocks 2022

### ISSUE THREAD

**Issue by Github-Aiko** [AikoXrayR-Project/XrayR#66]
**Mô tả chức năng bạn muốn**

Mô tả chức năng rõ ràng và ngắn gọn。

**Mô tả các lựa chọn thay thế bạn đã xem xét** 

Có bất kỳ lựa chọn thay thế nào để giải quyết vấn đề này không? 

**Bối cảnh bổ sung** 

Thêm bất kỳ bối cảnh hoặc ảnh chụp màn hình bổ sung nào về yêu cầu tính năng tại đây.

**Comment by AikoCute-Offical** [comment]
HMM
